name: WRKFLW salutation

on: workflow_dispatch

env:
  DAY_OF_WEEK: Lundi ## Variable d'environnement pour l'ensemble du flux de travail

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Salut ## Variable d'environnement pour la tâche
    steps:
      - name: "Step_Dites Salut Mona nous sommes lundi"
        run: |
          echo "$Greeting $First_Name. Nous sommes $DAY_OF_WEEK!"
          echo "Var repo1: ${VAR_ABO}"
          echo "Secret repo: ${{secrets.SECRET_ABO2}}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        env:
          First_Name: Mona ## Variable d'environnement uniquement pour l'étape 
